// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfRggfPXXZXBoIQWqQKHr4N7cWnt054Qk',
    appId: '1:173529259035:web:6bc4531ea958d99078acbe',
    messagingSenderId: '173529259035',
    projectId: 'test-modul3-c49f5',
    authDomain: 'test-modul3-c49f5.firebaseapp.com',
    storageBucket: 'test-modul3-c49f5.appspot.com',
    measurementId: 'G-WJ4CT0JBB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAd7adlHGP1OgHvyR9uX6Dsl-Qs8hcWnM',
    appId: '1:173529259035:android:f18a85f2c9a1300978acbe',
    messagingSenderId: '173529259035',
    projectId: 'test-modul3-c49f5',
    storageBucket: 'test-modul3-c49f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrvpxcHGNtcxkjMbhb4iPTlrC4Dvj93nU',
    appId: '1:173529259035:ios:2abdc548a67822e278acbe',
    messagingSenderId: '173529259035',
    projectId: 'test-modul3-c49f5',
    storageBucket: 'test-modul3-c49f5.appspot.com',
    iosBundleId: 'com.modul3.modul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrvpxcHGNtcxkjMbhb4iPTlrC4Dvj93nU',
    appId: '1:173529259035:ios:2abdc548a67822e278acbe',
    messagingSenderId: '173529259035',
    projectId: 'test-modul3-c49f5',
    storageBucket: 'test-modul3-c49f5.appspot.com',
    iosBundleId: 'com.modul3.modul3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfRggfPXXZXBoIQWqQKHr4N7cWnt054Qk',
    appId: '1:173529259035:web:dd0d584a3092194a78acbe',
    messagingSenderId: '173529259035',
    projectId: 'test-modul3-c49f5',
    authDomain: 'test-modul3-c49f5.firebaseapp.com',
    storageBucket: 'test-modul3-c49f5.appspot.com',
    measurementId: 'G-86VMV23GL5',
  );
}
